Solution/UmbracoCaches.Website/Controllers/DonutCacheController.cs
using System.Web.Mvc;
using DevTrends.MvcDonutCaching;
using Umbraco.Web.Models;
using Umbraco.Web.Mvc;

namespace UmbracoCaches.Website.Controllers
{
    public class DonutCacheController : RenderMvcController
    {
        [DonutOutputCache(Duration = 3600)]
        public override ActionResult Index(RenderModel model)
        {
            return base.Index(model);
        }
    }
}

Solution/UmbracoCaches.Website/Controllers/OutputCacheController.cs
using System.Web.Mvc;
using Umbraco.Web.Models;
using Umbraco.Web.Mvc;

namespace UmbracoCaches.Website.Controllers
{
    public class OutputCacheController : RenderMvcController
    {
        [OutputCache(Duration = 10)]
        public override ActionResult Index(RenderModel model)
        {
            // This page renders a partial with a thread sleep of 5000ms

            return base.Index(model);
        }
    }
}

Solution/UmbracoCaches.Website/Controllers/Surface/DonutSurfaceController.cs
using System.Web.Mvc;
using Umbraco.Web.Mvc;

namespace UmbracoCaches.Website.Controllers.Surface
{
    public class DonutSurfaceController : SurfaceController
    {
        [ChildActionOnly]
        public ActionResult Timestamp()
        {
            return PartialView("_Timestamp"); //located in ~/views/donutsurfacecontroller/_Timestamp.cshtml
        }
    }
}

Solution/UmbracoCaches.Website/Views/CachedPartial.cshtml
@inherits UmbracoTemplatePage

@section Supercharger
{
    <!--supercharger-o-meter-->
}

<section id="call">
    <h3 class="text-center banner divider">Cached Partial</h3>
    <div class="container">
        <div class="col-md-12">
            <p class="text-center intro">
                This gallery is served via a cached <strong>MVC Partial</strong> named 'Gallery List'. The cache purges every 5 seconds.
                <br/>
                Just to make things obvious if the gallery isnt coming from cache it also has a deliberate <strong>5 second delay</strong>.
            </p>
        </div>
        


        @Html.CachedPartial("_GalleryList", null, 5)
        
        

        <h4 class="text-center banner divider">The Code</h4>
        <div class="col-md-12">
            <div>
                <pre><code>@@Html.CachedPartial("_GalleryList", null, 5000)</code></pre>
            </div>

            <div>
                <pre><code>IHtmlString CachedPartial(
                    string partialViewName,
                    object model,
                    int cachedSeconds,
                    bool cacheByPage = false,
                    bool cacheByMember = false,
                    ViewDataDictionary viewData = null)
                </code></pre>
            </div>
        </div>

    </div>
</section>

Solution/UmbracoCaches.Website/Views/DonutCache.cshtml
@inherits UmbracoTemplatePage

<section id="call">
    <h3 class="text-center banner divider">Donut Output Cache</h3>
    <div class="container">
        <div class="col-md-12">
            <p class="text-center intro">
                This page is served using the <strong>Dounut Cache</strong>. The main action is cached for one hour but will clear with a publish.
            </p>
        </div>
        
        <div class="col-md-12">
            <div class="bs-callout bs-callout-info">
                <h5>Main view last generated @DateTime.Now.ToString("HH:mm:ss tt")</h5>
            </div>
        </div>
        
        <div class="col-md-12"><p class="info"> </p></div>
        
        <p>
            The timestamp below is specified to be excluded from the parent cache (the donut hole).
            So on render the timestamp will update very time where the timestamp above remains constant.
        </p>

    

        <h4 class="text-center banner divider">The donut hole</h4>
        @Html.Action("Timestamp", "DonutSurface", true)
        
        

        <div class="col-md-12"><p class="info"> </p></div>

        <h4 class="text-center banner divider">The Code</h4>
        <div class="col-md-12">
            <div>
                <pre><code>@@Html.Action("Timestamp", "DonutSurface", true)</code></pre>
            </div>
        </div>
    </div>
</section>

Solution/UmbracoCaches.Website/Views/DonutSurface/_Timestamp.cshtml
@{
    Layout = null;
}

<div class="col-md-12">
    <div class="bs-callout bs-callout-info">
        <h5>Timestamp at @DateTime.Now.ToString("HH:mm:ss tt")</h5>
    </div>
</div>

Solution/UmbracoCaches.Website/Views/Global.cshtml
@inherits UmbracoTemplatePage
@{
    Layout = null;
}
@*http://getbootstrap.com/examples/theme/*@
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">
        <title>Umbraco Caches</title>
    
        <!-- Bootstrap core CSS -->
        <link href="/css/bootstrap.min.css" rel="stylesheet">
        <!-- Bootstrap theme -->
        <link href="/css/bootstrap-theme.min.css" rel="stylesheet">

        <!-- Custom styles for this template -->
        <link href="/css/theme.css" rel="stylesheet">

        <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->

    </head>
    <body role="document">
        
        @RenderSection("Supercharger", false)     
        
        <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/"></a>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li><a href="/">Home</a></li>
                        <li><a href="/macro-cache/">Macro Cache</a></li>
                        <li><a href="/cached-partial/">Cached Partial</a></li>
                        <li><a href="/output-cache/">Output Cache</a></li>
                        <li><a href="/donut-cache/">Donut Cache</a></li>
                        <li><a href="/varnish/">Varnish</a></li>
                    </ul>
                </div>
            </div>
        </div>

        <div class="container" role="main">
            
            @RenderBody()

        </div>

        <!-- Bootstrap core JavaScript
            ================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
        <script src="/scripts/bootstrap.min.js"></script>
        <script src="/scripts/docs.min.js"></script>
    </body>
</html>

Solution/UmbracoCaches.Website/Views/Home.cshtml
@inherits UmbracoTemplatePage
@{
   
}

<h3 class="text-center banner divider">Umbraco Caches</h3>
<div class="col-md-12">
    <p class="text-right intro">Demo'd at Codegarden 2014, Copenhagen</p>
</div>
<div class="col-md-10 col-md-offset-1">
    <h4 id="siteTagline" class="text-center info">This is a website showcasing how you can Supercharge your Umbraco website.</h4>
</div>
<div class="col-md-10 col-md-offset-1">
    <p class="text-center info">Warning most pages on this site have page load delays purposefully built in.</p>
</div>

Solution/UmbracoCaches.Website/Views/MacroCache.cshtml
@inherits UmbracoTemplatePage

@section Supercharger
{
    <!--supercharger-o-meter-->
}

<section id="call">
    <h3 class="text-center banner divider">Macro Cache</h3>
    <div class="container">
        <div class="col-md-12">
            <p class="text-center intro">
                This gallery is served via a cached <strong>Macro</strong> named 'Gallery List'. The cache purges every 5 seconds.
                <br/>
                Just to make things obvious if the gallery isnt coming from cache it also has a deliberate <strong>5 second delay</strong>.
            </p>
        </div>
        
        

        @Umbraco.RenderMacro("GalleryList")
        
        
        
        <h4 class="text-center banner divider">The Code</h4>
        <div class="col-md-12">
            <div>
                <pre><code>@@Umbraco.RenderMacro("GalleryList")</code></pre>
            </div>
            
            <div>
                <pre><code>IHtmlString RenderMacro(
                    string alias, 
                    object parameters)
                </code></pre>
            </div>
            
        </div>
    </div>
</section>

Solution/UmbracoCaches.Website/Views/MacroPartials/GalleryList.cshtml
@using System.Threading
@inherits Umbraco.Web.Macros.PartialViewMacroPage
@{
    Thread.Sleep(5000);
}
<div class="row">
    <div class="col-md-4">
        <a class="thumbnail" href="#">
            <img class="img-responsive" src="/Images/1.jpg" />
        </a>
    </div>
    <div class="col-md-4">
        <a class="thumbnail" href="#">
            <img class="img-responsive" src="/Images/2.jpg" />
        </a>
    </div>
    <div class="col-md-4">
        <a class="thumbnail" href="#">
            <img class="img-responsive" src="/Images/3.jpg" />
        </a>
    </div>
    <div class="col-md-4">
        <a class="thumbnail" href="#">
            <img class="img-responsive" src="/Images/4.jpg" />
        </a>
    </div>
    <div class="col-md-4">
        <a class="thumbnail" href="#">
            <img class="img-responsive" src="/Images/5.jpg" />
        </a>
    </div>
    <div class="col-md-4">
        <a class="thumbnail" href="#">
            <img class="img-responsive" src="/Images/6.jpg" />
        </a>
    </div>
</div>

 

Solution/UmbracoCaches.Website/Views/OutputCache.cshtml
@inherits UmbracoTemplatePage

@section Supercharger
{
    <div class="container">
        <div class="col-md-12">
            <div class="bs-callout bs-callout-info">
                <h4>This page was last generated @DateTime.Now.ToString("HH:mm:ss tt")</h4>
            </div>
        </div>
    </div>
}
<section id="call">
    <h3 class="text-center banner divider">MVC Output Cache</h3>
    <div class="container">
        <div class="col-md-12">
            <p class="text-center intro">
                This gallery is served using the <strong>MVC Output Cache</strong>. The cache will purge every 10 seconds.
                <br />
                Just to make things obvious if the gallery isnt coming from cache it also has a deliberate <strong>5 second delay</strong>.
            </p>
        </div>


        <!-- This does not have anything to do with caching
            we're simply re-using the markup in the partial -->
        @Html.Partial("_GalleryList")



        <h4 class="text-center banner divider">The Code</h4>
        <div class="col-md-12">
            <div>
                <pre><code>[OutputCache(Duration = 10)]</code></pre>
            </div>
        </div>
    </div>
</section>

Solution/UmbracoCaches.Website/Views/Partials/_GalleryList.cshtml
@using System.Threading
@{
    Thread.Sleep(5000);
}
<div class="row">
    <div class="col-md-4">
        <a class="thumbnail" href="#">
            <img class="img-responsive" src="/Images/1.jpg" />
        </a>
    </div>
    <div class="col-md-4">
        <a class="thumbnail" href="#">
            <img class="img-responsive" src="/Images/2.jpg" />
        </a>
    </div>
    <div class="col-md-4">
        <a class="thumbnail" href="#">
            <img class="img-responsive" src="/Images/3.jpg" />
        </a>
    </div>
    <div class="col-md-4">
        <a class="thumbnail" href="#">
            <img class="img-responsive" src="/Images/4.jpg" />
        </a>
    </div>
    <div class="col-md-4">
        <a class="thumbnail" href="#">
            <img class="img-responsive" src="/Images/5.jpg" />
        </a>
    </div>
    <div class="col-md-4">
        <a class="thumbnail" href="#">
            <img class="img-responsive" src="/Images/6.jpg" />
        </a>
    </div>
</div>

Solution/UmbracoCaches.Website/Views/Varnish.cshtml
@inherits UmbracoTemplatePage

<h3 class="text-center">Last generated</h3>
<h3 class="text-center">@DateTime.Now.ToString("HH:mm:ss tt")</h3>
<div class="col-md-12">
    <p class="text-center info">
        When ran through a varnish cache such as <br/>
        <a href="http://varnish.umbracocaches.detangled-digital.com/varnish/" target="_blank">http://varnish.umbracocaches.detangled-digital.com/varnish/</a><br/>
        this dynamic time stamp will become static between CMS publishes<br/>
        with a handler to <a href="https://www.varnish-cache.org/docs/3.0/tutorial/purging.html" target="_blank">run a PURGE</a>.
    </p>
</div>